# Highly relevant authors like this one are added by Konbini itself, not their owners.
# If you're this author, simply make a PR removing this comment and modifying this manifest to your liking.
# If this is here, it's because at least a package of yours was also added to Konbini.
name: "Meta"
website: meta.com
type: PRIVATE_CORP
biography: "We're building the future of human connection. And the technologies that make it possible." # copied from their website's about
hiring: true # they always are, right?
socials:
  twitter: Meta
  github: facebook
